<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/LocationDbAdapter" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="http://xmlns.antonislogothetis.com/DatabaseAdapter/Example/Schema" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://xmlns.antonislogothetis.com/DatabaseAdapter/Example/LocationHandlerProcess"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/soa/DatabaseAdapter/LocationDbAdapter"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/LocationHandlerProcess.wsdl"/>
            <oracle-xsl-mapper:rootElement name="mergeLocationsRequest" namespace="http://xmlns.antonislogothetis.com/DatabaseAdapter/Example/Schema"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/LocationDbAdapter.wsdl"/>
            <oracle-xsl-mapper:rootElement name="LocationsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/LocationDbAdapter"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [MON MAR 05 23:55:02 EET 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:LocationsCollection>
         <xsl:for-each select="/ns0:mergeLocationsRequest/ns0:Locations">
            <tns:Locations>
               <tns:locationId>
                  <xsl:value-of select="ns0:locationId"/>
               </tns:locationId>
               <tns:streetAddress>
                  <xsl:value-of select="ns0:streetAddress"/>
               </tns:streetAddress>
               <tns:postalCode>
                  <xsl:value-of select="ns0:postalCode"/>
               </tns:postalCode>
               <tns:city>
                  <xsl:value-of select="ns0:city"/>
               </tns:city>
               <tns:stateProvince>
                  <xsl:value-of select="ns0:stateProvince"/>
               </tns:stateProvince>
               <tns:countryId>
                  <xsl:value-of select="ns0:countryId"/>
               </tns:countryId>
            </tns:Locations>
         </xsl:for-each>
      </tns:LocationsCollection>
   </xsl:template>
</xsl:stylesheet>
